resources:
  containers:
    - container: ubuntu_x64_build_container
      image: microsoft/dotnet-buildtools-prereqs:ubuntu-16.04-c103199-20180628134544
    # - container: ubuntu_1604_arm64_cross_container
    #   image: microsoft/dotnet-buildtools-prereqs:ubuntu-16.04-cross-arm64-a3ae44b-20180315221921

# CI Trigger on master branch
trigger:
  branches:
    include:
    - master
  paths:
    exclude: # don't trigger the CI if only a doc file was changed
    - docs/*
    - eng/common/README.md
    - src/benchmarks/micro/Serializers/README.md
    - src/benchmarks/micro/README.md
    - src/benchmarks/real-world/JitBench/README.md
    - src/benchmarks/real-world/Microsoft.ML.Benchmarks/Input/README.md
    - src/tools/ResultsComparer/README.md
    - README.md

# Trigger builds for PR's targeting master
pr:
  branches:
    include:
    - master
  paths:
    exclude: # don't trigger the CI if only a doc file was changed
    - docs/*
    - eng/common/README.md
    - src/benchmarks/micro/Serializers/README.md
    - src/benchmarks/micro/README.md
    - src/benchmarks/real-world/JitBench/README.md
    - src/benchmarks/real-world/Microsoft.ML.Benchmarks/Input/README.md
    - src/tools/ResultsComparer/README.md
    - README.md

jobs:

# Ubuntu 1604 x64 ML.NET benchmarks, public correctness job
- ${{ if eq(variables['System.TeamProject'], 'public') }}:
  - template: /eng/performance/benchmark_jobs.yml
    parameters:
      osName: ubuntu
      osVersion: 1604
      kind: mlnet
      architecture: x64
      pool: Hosted Ubuntu 1604
      queue: Ubuntu.1604.Amd64.Open
      container: ubuntu_x64_build_container
      runCategories: 'mldotnet'
      csproj: src/benchmarks/real-world/Microsoft.ML.Benchmarks/Microsoft.ML.Benchmarks.csproj
      frameworks: # for ML.NET jobs we want to check .NET Core 3.0 only
        - netcoreapp3.0
        