resources:
  containers:
    - container: ubuntu_x64_build_container
      image: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-20210311173856-047508b

# CI Trigger on main branch
trigger:
  branches:
    include:
    - main
    - release/3.1.4xx
  paths:
    include:
    - eng/Version.Details.xml

# Trigger builds for PR's targeting main
pr:
  branches:
    include:
    - main
  paths:
    exclude: # don't trigger the CI if only a doc file was changed
    - docs/*
    - eng/common/README.md
    - src/benchmarks/micro/Serializers/README.md
    - src/benchmarks/micro/README.md
    - src/benchmarks/real-world/JitBench/README.md
    - src/benchmarks/real-world/Microsoft.ML.Benchmarks/Input/README.md
    - src/tools/ResultsComparer/README.md
    - README.md

schedules:
- cron: "0 */12 * * *"
  displayName: Every 12 hours build
  branches:
    include:
    - main
  always: true

jobs:

######################################################
# Public correctness jobs
######################################################

- ${{ if eq(variables['System.TeamProject'], 'public') }}:
  # Windows x64 scenario benchmarks
  - template: /eng/performance/scenarios.yml
    parameters:
      osName: windows
      osVersion: 21H1
      architecture: x64
      pool:
        vmImage: windows-2019
      kind: scenarios
      machinePool: Open
      queue: Windows.10.Amd64.Client21H1.Open
      projectFile: scenarios.proj
      channels: # for public jobs we want to make sure that the PRs don't break any of the supported frameworks
        - main

  # Ubuntu 1804 x64 scenario benchmarks
  - template: /eng/performance/scenarios.yml
    parameters:
      osName: ubuntu
      osVersion: 1804
      kind: scenarios
      architecture: x64
      pool: 
        vmImage: ubuntu-latest
      machinePool: Open
      queue: Ubuntu.1804.Amd64.Open
      container: ubuntu_x64_build_container
      projectFile: scenarios.proj
      channels:
        - main
  
  # Windows x64 Blazor scenario benchmarks
  - template: /eng/performance/scenarios.yml
    parameters:
      osName: windows
      osVersion: 21H1
      architecture: x64
      pool:
        vmImage: windows-2019
      kind: blazor_scenarios
      machinePool: Open
      queue: Windows.10.Amd64.Client21H1.Open
      projectFile: blazor_scenarios.proj
      channels:
        - main

  # Windows x64 SDK scenario benchmarks
  - template: /eng/performance/scenarios.yml
    parameters:
      osName: windows
      osVersion: 21H1
      architecture: x64
      pool:
        vmImage: windows-2019
      kind: sdk_scenarios
      machinePool: Open
      queue: Windows.10.Amd64.Client21H1.Open
      projectFile: sdk_scenarios.proj
      channels:
        - main
  
  # Ubuntu 1804 x64 SDK scenario benchmarks
  - template: /eng/performance/scenarios.yml
    parameters:
      osName: ubuntu
      osVersion: 1804
      kind: sdk_scenarios
      architecture: x64
      pool: 
        vmImage: ubuntu-latest
      machinePool: Open
      queue: Ubuntu.1804.Amd64.Open
      container: ubuntu_x64_build_container
      projectFile: sdk_scenarios.proj
      channels:
        - main

  # Windows x86 SDK scenario benchmarks
  - template: /eng/performance/scenarios.yml
    parameters:
      osName: windows
      osVersion: 21H1
      architecture: x86
      pool:
        vmImage: windows-2019
      kind: sdk_scenarios
      machinePool: Open
      queue: Windows.10.Amd64.Client21H1.Open
      projectFile: sdk_scenarios.proj
      channels:
        - main

###########################################
# Private Jobs
###########################################

- ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest', 'Manual')) }}:

  # Windows x64 scenario benchmarks
  - template: /eng/performance/scenarios.yml
    parameters:
      osName: windows
      osVersion: 19H1
      architecture: x64
      pool:
        vmImage: windows-2019
      kind: scenarios
      machinePool: Tiger
      queue: Windows.10.Amd64.19H1.Tiger.Perf
      projectFile: scenarios.proj
      channels: # for public jobs we want to make sure that the PRs don't break any of the supported channels
        - main

  # Ubuntu 1804 x64 scenario benchmarks
  - template: /eng/performance/scenarios.yml
    parameters:
      osName: ubuntu
      osVersion: 1804
      kind: scenarios
      architecture: x64
      pool: 
        vmImage: ubuntu-latest
      machinePool: Tiger
      queue: Ubuntu.1804.Amd64.Tiger.Perf # using a dedicated private Helix queue (perftigers)
      container: ubuntu_x64_build_container
      projectFile: scenarios.proj
      channels:
        - main

################################################
# Scheduled Private jobs
################################################

# Scheduled runs will run all of the jobs on the PerfTigers, as well as the Arm64 job
- ${{ if and(ne(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'Schedule')) }}:

  # Windows x64 SDK scenario benchmarks
  - template: /eng/performance/scenarios.yml
    parameters:
      osName: windows
      osVersion: RS5
      architecture: x64
      pool:
        vmImage: windows-2019
      kind: sdk_scenarios
      machinePool: Tiger
      queue: Windows.10.Amd64.19H1.Tiger.Perf
      projectFile: sdk_scenarios.proj
      channels:
        - main
  
  # Windows x86 SDK scenario benchmarks
  - template: /eng/performance/scenarios.yml
    parameters:
      osName: windows
      osVersion: RS5
      architecture: x86
      pool:
        vmImage: windows-2019
      kind: sdk_scenarios
      machinePool: Tiger
      queue: Windows.10.Amd64.19H1.Tiger.Perf
      projectFile: sdk_scenarios.proj
      channels:
        - main

  # Ubuntu 1804 x64 SDK scenario benchmarks
  - template: /eng/performance/scenarios.yml
    parameters:
      osName: ubuntu
      osVersion: 1804
      architecture: x64
      pool: 
        vmImage: ubuntu-latest
      kind: sdk_scenarios
      machinePool: Tiger
      queue: Ubuntu.1804.Amd64.Tiger.Perf
      container: ubuntu_x64_build_container
      projectFile: sdk_scenarios.proj
      channels:
        - main

  # Windows x64 Blazor 3.2 scenario benchmarks
  - template: /eng/performance/scenarios.yml
    parameters:
      osName: windows
      osVersion: RS5
      architecture: x64
      pool:
        vmImage: windows-2019
      kind: blazor_scenarios
      machinePool: Tiger
      queue: Windows.10.Amd64.19H1.Tiger.Perf
      projectFile: blazor_scenarios.proj
      channels:
        - main

################################################
# Manually Triggered Job
################################################


- ${{ if and(ne(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'Manual')) }}:

  # Windows x64 SDK scenario benchmarks
  - template: /eng/performance/scenarios.yml
    parameters:
      osName: windows
      osVersion: RS5
      architecture: x64
      pool:
        vmImage: windows-2019
      kind: sdk_scenarios
      machinePool: Tiger
      queue: Windows.10.Amd64.19H1.Tiger.Perf
      projectFile: sdk_scenarios.proj
      channels:
        - $(channel) # for manual runs we can specify channel variable 

  # Windows x86 SDK scenario benchmarks
  - template: /eng/performance/scenarios.yml
    parameters:
      osName: windows
      osVersion: RS5
      architecture: x86
      pool:
        vmImage: windows-2019
      kind: sdk_scenarios
      machinePool: Tiger
      queue: Windows.10.Amd64.19H1.Tiger.Perf
      projectFile: sdk_scenarios.proj
      channels:
        - $(channel) # for manual runs we can specify channel variable 

  # Ubuntu 1804 x64 SDK scenario benchmarks
  - template: /eng/performance/scenarios.yml
    parameters:
      osName: ubuntu
      osVersion: 1804
      architecture: x64
      pool:
        vmImage: ubuntu-latest
      kind: sdk_scenarios
      machinePool: Tiger
      queue: Ubuntu.1804.Amd64.Tiger.Perf
      container: ubuntu_x64_build_container
      projectFile: sdk_scenarios.proj
      channels:
        - $(channel)
